### ISSUE TITLE
Download Demo Fail

### ISSUE THREAD

**Issue by thiagoe** [hgruber/zabbix-d3js-widgets#5]
i like so much this project but..
When i use your url for acess demo this all ok, open all widgets and maps

When i downloaded for my pc and open sample.html only load image but dont load any widget tip for this problem?

**Comment by hgruber** [comment]
it looks like incompatibilities of releases in version 3 of d3.js. I use a feature that is not supported in a later release of version 3. To quickly resolve this problem I added jquery and d3.v3.min.js so that a local copy of this project works out of the box.
Updating to version 4 of d3.js is a pending issue though...
